-- futur•e
-- Etape suivante: couche d'indicateurs normalisés par commune.
-- A lancer dans Supabase > SQL Editor après 01_init_catalog.sql et 02_init_qna.sql.

begin;

create table if not exists public.source_datasets (
  id text primary key,
  source_name text not null,
  producer text,
  dataset_name text not null,
  dataset_version text,
  source_url text,
  license text,
  update_frequency text,
  geographic_granularity text,
  notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.indicator_definitions (
  code text primary key,
  label text not null,
  description text,
  unit text,
  theme text not null,
  source_dataset_id text references public.source_datasets (id) on delete set null,
  value_kind text not null default 'numeric',
  default_scenario text,
  default_horizon text,
  metadata jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.drias_grid_points (
  dataset_id text not null references public.source_datasets (id) on delete cascade,
  point_id text not null,
  latitude double precision not null,
  longitude double precision not null,
  nearest_insee text,
  nearest_commune_name text,
  distance_km double precision,
  warming_level text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (dataset_id, point_id, warming_level)
);

create table if not exists public.commune_indicators (
  id bigint generated by default as identity primary key,
  insee_code text not null,
  commune_name text,
  indicator_code text not null references public.indicator_definitions (code) on delete cascade,
  source_dataset_id text references public.source_datasets (id) on delete set null,
  scenario text,
  horizon text,
  value_numeric double precision,
  value_text text,
  unit text,
  source_ref text,
  geography_kind text not null default 'commune',
  coverage text,
  confidence text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint commune_indicators_value_check
    check (value_numeric is not null or value_text is not null)
);

create unique index if not exists commune_indicators_unique_measure
  on public.commune_indicators (
    insee_code,
    indicator_code,
    coalesce(source_dataset_id, ''),
    coalesce(scenario, ''),
    coalesce(horizon, '')
  );

create index if not exists commune_indicators_lookup_idx
  on public.commune_indicators (insee_code, indicator_code);

create index if not exists commune_indicators_source_idx
  on public.commune_indicators (source_dataset_id, scenario, horizon);

create index if not exists commune_indicators_metadata_gin
  on public.commune_indicators using gin (metadata);

create index if not exists drias_grid_points_nearest_idx
  on public.drias_grid_points (nearest_insee, warming_level);

insert into public.source_datasets (
  id,
  source_name,
  producer,
  dataset_name,
  dataset_version,
  source_url,
  license,
  update_frequency,
  geographic_granularity,
  notes
)
values
  (
    'drias_tracc_indices',
    'DRIAS',
    'Météo-France / TRACC',
    'Indices climatiques DRIAS par point de grille',
    'v1',
    'https://www.drias-climat.fr/',
    'Etalab / licence publique selon jeu source',
    'ponctuelle selon publication',
    'point de grille rapproché à la commune',
    'Source de base pour chaleur, nuits tropicales, précipitations et signaux climatiques structurants.'
  )
on conflict (id) do update
set
  source_name = excluded.source_name,
  producer = excluded.producer,
  dataset_name = excluded.dataset_name,
  dataset_version = excluded.dataset_version,
  source_url = excluded.source_url,
  license = excluded.license,
  update_frequency = excluded.update_frequency,
  geographic_granularity = excluded.geographic_granularity,
  notes = excluded.notes,
  is_active = true,
  updated_at = now();

insert into public.indicator_definitions (
  code,
  label,
  description,
  unit,
  theme,
  source_dataset_id,
  value_kind,
  default_scenario,
  default_horizon,
  metadata
)
values
  (
    'NORTMm_yr',
    'Température moyenne annuelle',
    'Projection DRIAS de la température moyenne annuelle.',
    '°C',
    'climat',
    'drias_tracc_indices',
    'numeric',
    'median',
    '2050',
    jsonb_build_object('family', 'temperature', 'default_warming_level', 'GWL20')
  ),
  (
    'NORTMm_seas_JJA',
    'Température moyenne d’été',
    'Projection DRIAS de la température moyenne estivale.',
    '°C',
    'climat',
    'drias_tracc_indices',
    'numeric',
    'median',
    '2050',
    jsonb_build_object('family', 'temperature', 'season', 'JJA', 'default_warming_level', 'GWL20')
  ),
  (
    'NORTXm_seas_JJA',
    'Température maximale d’été',
    'Projection DRIAS de la température maximale estivale.',
    '°C',
    'climat',
    'drias_tracc_indices',
    'numeric',
    'median',
    '2050',
    jsonb_build_object('family', 'temperature', 'season', 'JJA', 'default_warming_level', 'GWL20')
  ),
  (
    'NORTX30D_yr',
    'Jours à plus de 30°C',
    'Nombre annuel de jours où la température maximale dépasse 30°C.',
    'jours/an',
    'climat',
    'drias_tracc_indices',
    'numeric',
    'median',
    '2050',
    jsonb_build_object('family', 'heat_days', 'threshold_c', 30, 'default_warming_level', 'GWL20')
  ),
  (
    'NORTX35D_yr',
    'Jours à plus de 35°C',
    'Nombre annuel de jours où la température maximale dépasse 35°C.',
    'jours/an',
    'climat',
    'drias_tracc_indices',
    'numeric',
    'median',
    '2050',
    jsonb_build_object('family', 'heat_days', 'threshold_c', 35, 'default_warming_level', 'GWL20')
  ),
  (
    'NORTR_yr',
    'Nuits tropicales',
    'Nombre annuel de nuits tropicales selon DRIAS.',
    'nuits/an',
    'climat',
    'drias_tracc_indices',
    'numeric',
    'median',
    '2050',
    jsonb_build_object('family', 'night_heat', 'default_warming_level', 'GWL20')
  ),
  (
    'NORRR_yr',
    'Précipitations annuelles',
    'Projection DRIAS du cumul annuel de précipitations.',
    'mm/an',
    'climat',
    'drias_tracc_indices',
    'numeric',
    'median',
    '2050',
    jsonb_build_object('family', 'precipitation', 'default_warming_level', 'GWL20')
  ),
  (
    'NORRR_seas_JJA',
    'Précipitations d’été',
    'Projection DRIAS du cumul estival de précipitations.',
    'mm',
    'climat',
    'drias_tracc_indices',
    'numeric',
    'median',
    '2050',
    jsonb_build_object('family', 'precipitation', 'season', 'JJA', 'default_warming_level', 'GWL20')
  ),
  (
    'NORRR_seas_DJF',
    'Précipitations d’hiver',
    'Projection DRIAS du cumul hivernal de précipitations.',
    'mm',
    'climat',
    'drias_tracc_indices',
    'numeric',
    'median',
    '2050',
    jsonb_build_object('family', 'precipitation', 'season', 'DJF', 'default_warming_level', 'GWL20')
  )
on conflict (code) do update
set
  label = excluded.label,
  description = excluded.description,
  unit = excluded.unit,
  theme = excluded.theme,
  source_dataset_id = excluded.source_dataset_id,
  value_kind = excluded.value_kind,
  default_scenario = excluded.default_scenario,
  default_horizon = excluded.default_horizon,
  metadata = excluded.metadata,
  is_active = true,
  updated_at = now();

alter table public.source_datasets enable row level security;
alter table public.indicator_definitions enable row level security;
alter table public.drias_grid_points enable row level security;
alter table public.commune_indicators enable row level security;

drop policy if exists "public read source_datasets" on public.source_datasets;
create policy "public read source_datasets"
on public.source_datasets
for select
to anon, authenticated
using (is_active = true);

drop policy if exists "public read indicator_definitions" on public.indicator_definitions;
create policy "public read indicator_definitions"
on public.indicator_definitions
for select
to anon, authenticated
using (is_active = true);

drop policy if exists "public read drias_grid_points" on public.drias_grid_points;
create policy "public read drias_grid_points"
on public.drias_grid_points
for select
to anon, authenticated
using (true);

drop policy if exists "public read commune_indicators" on public.commune_indicators;
create policy "public read commune_indicators"
on public.commune_indicators
for select
to anon, authenticated
using (true);

commit;

-- Vérifications rapides après exécution :
-- select count(*) from public.source_datasets;
-- select count(*) from public.indicator_definitions;
-- select count(*) from public.commune_indicators;
