-- futur•e Pro — inscriptions avant-première professionnelle
-- À lancer dans Supabase > SQL Editor

begin;

create table if not exists public.pro_inscriptions (
  id          bigint generated by default as identity primary key,
  profession  text not null,
  email       text not null,
  cabinet     text,
  besoin      text,
  created_at  timestamptz not null default now()
);

create index if not exists pro_inscriptions_email_idx on public.pro_inscriptions (email);
create index if not exists pro_inscriptions_profession_idx on public.pro_inscriptions (profession);

alter table public.pro_inscriptions enable row level security;

-- Lecture réservée aux admins (service role uniquement)
-- Écriture publique (le formulaire utilise la clé anon)
drop policy if exists "anon insert pro_inscriptions" on public.pro_inscriptions;
create policy "anon insert pro_inscriptions"
on public.pro_inscriptions
for insert
to anon, authenticated
with check (true);

commit;
